apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name : express-api
          image: darkcoder347/saarthak:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000   