apiVersion: v1
kind: Service
metadata:
  name: express-api
spec:
  type: NodePort
  selector:
    app: express-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100
  
